In [1]:
%reload_ext autoreload

In [2]:
%autoreload

In [3]:
%aimport shift_pod

torch.Size([200, 204]) torch.Size([200, 204])
tensor(80.3652, dtype=torch.float64, grad_fn=<AddBackward0>) tensor(1., dtype=torch.float64)
tensor(80.3652, dtype=torch.float64, grad_fn=<AddBackward0>) tensor(1., dtype=torch.float64)


In [14]:
%run -i shift_pod

torch.Size([200, 204]) torch.Size([200, 204])
tensor(80.3567, dtype=torch.float64, grad_fn=<AddBackward0>) tensor(1., dtype=torch.float64)
tensor(80.3567, dtype=torch.float64, grad_fn=<AddBackward0>) tensor(1., dtype=torch.float64)


In [55]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
v = 3.5

In [60]:
x_min = (a - v).argmin()
print(x_min)
print(a[x_min])

0
1


In [15]:
x_db.T[2]

tensor([0.0000, 0.0300, 0.0500, 0.0800, 0.1000, 0.1300, 0.1500, 0.1800, 0.2000,
        0.2300, 0.2500, 0.2800, 0.3000, 0.3300, 0.3500, 0.3800, 0.4000, 0.4300,
        0.4500, 0.4800, 0.5000, 0.5300, 0.5500, 0.5800, 0.6000, 0.6300, 0.6500,
        0.6800, 0.7000, 0.7300, 0.7500, 0.7800, 0.8000, 0.8300, 0.8500, 0.8800,
        0.9000, 0.9300, 0.9500, 0.9800, 1.0100, 1.0300, 1.0600, 1.0800, 1.1100,
        1.1300, 1.1600, 1.1800, 1.2100, 1.2300, 1.2600, 1.2800, 1.3100, 1.3300,
        1.3600, 1.3800, 1.4100, 1.4300, 1.4600, 1.4800, 1.5100, 1.5300, 1.5600,
        1.5800, 1.6100, 1.6300, 1.6600, 1.6800, 1.7100, 1.7300, 1.7600, 1.7800,
        1.8100, 1.8300, 1.8600, 1.8800, 1.9100, 1.9300, 1.9600, 1.9800, 2.0100,
        2.0400, 2.0600, 2.0900, 2.1100, 2.1400, 2.1600, 2.1900, 2.2100, 2.2400,
        2.2600, 2.2900, 2.3100, 2.3400, 2.3600, 2.3900, 2.4100, 2.4400, 2.4600,
        2.4900, 2.5100, 2.5400, 2.5600, 2.5900, 2.6100, 2.6400, 2.6600, 2.6900,
        2.7100, 2.7400, 2.7600, 2.7900, 

In [38]:
x_db

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0300, 0.0300, 0.0300,  ..., 0.0300, 0.0300, 0.0300],
        [0.0500, 0.0500, 0.0500,  ..., 0.0500, 0.0500, 0.0500],
        ...,
        [4.9500, 4.9500, 4.9500,  ..., 4.9500, 4.9500, 4.9500],
        [4.9700, 4.9700, 4.9700,  ..., 4.9700, 4.9700, 4.9700],
        [5.0000, 5.0000, 5.0000,  ..., 5.0000, 5.0000, 5.0000]],
       dtype=torch.float64, grad_fn=<PermuteBackward>)

In [43]:
x_db[3].shape

torch.Size([204])

In [44]:
x_db.shape

torch.Size([200, 204])

In [65]:
x_db[:,0]

tensor([0.0000, 0.0300, 0.0500, 0.0800, 0.1000, 0.1300, 0.1500, 0.1800, 0.2000,
        0.2300, 0.2500, 0.2800, 0.3000, 0.3300, 0.3500, 0.3800, 0.4000, 0.4300,
        0.4500, 0.4800, 0.5000, 0.5300, 0.5500, 0.5800, 0.6000, 0.6300, 0.6500,
        0.6800, 0.7000, 0.7300, 0.7500, 0.7800, 0.8000, 0.8300, 0.8500, 0.8800,
        0.9000, 0.9300, 0.9500, 0.9800, 1.0100, 1.0300, 1.0600, 1.0800, 1.1100,
        1.1300, 1.1600, 1.1800, 1.2100, 1.2300, 1.2600, 1.2800, 1.3100, 1.3300,
        1.3600, 1.3800, 1.4100, 1.4300, 1.4600, 1.4800, 1.5100, 1.5300, 1.5600,
        1.5800, 1.6100, 1.6300, 1.6600, 1.6800, 1.7100, 1.7300, 1.7600, 1.7800,
        1.8100, 1.8300, 1.8600, 1.8800, 1.9100, 1.9300, 1.9600, 1.9800, 2.0100,
        2.0400, 2.0600, 2.0900, 2.1100, 2.1400, 2.1600, 2.1900, 2.2100, 2.2400,
        2.2600, 2.2900, 2.3100, 2.3400, 2.3600, 2.3900, 2.4100, 2.4400, 2.4600,
        2.4900, 2.5100, 2.5400, 2.5600, 2.5900, 2.6100, 2.6400, 2.6600, 2.6900,
        2.7100, 2.7400, 2.7600, 2.7900, 

In [76]:
y_db[:, 0]

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0100, 0.0100, 0.0100, 0.0200, 0.0300,
        0.0500, 0.0700, 0.1000, 0.1400, 0.1900, 0.2500, 0.3400, 0.4300, 0.5500,
        0.6900, 0.8300, 1.0000, 1.1700, 1.3400, 1.5000, 1.6600, 1.7900, 1.8900,
        1.9600, 1.9900, 1.9900, 1.9400, 1.8500, 1.7400, 1.6000, 1.4400, 1.2700,
        1.1000, 0.9300, 0.7700, 0.6300, 0.5000, 0.3900, 0.3000, 0.2300, 0.1700,
        0.1200, 0.0800, 0.0600, 0.0400, 0.0300, 0.0200, 0.0100, 0.0100, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,
        -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,
        -0.0000, -0.0000

In [100]:
a = range(0, 11, 2)

In [114]:
b = np.arange(0, 4.5, 0.5)

In [118]:
c = zip(a, b)

In [119]:
print(set(c))

{(0, 0.0), (8, 2.0), (6, 1.5), (2, 0.5), (4, 1.0), (10, 2.5)}


In [128]:
for i, j in zip(a, b):
    print(i)
    print(j)

0
0.0
2
0.5
4
1.0
6
1.5
8
2.0
10
2.5
